//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.ProductSales = new HashSet<ProductSales>();
        }
    
        public int productID { get; set; }
        public string name { get; set; }
        public int amount { get; set; }
        public decimal price { get; set; }
    
        public virtual ICollection<ProductSales> ProductSales { get; set; }
    }
}
