//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSales
    {
        public int productsaleID { get; set; }
        public int productID { get; set; }
        public int amount { get; set; }
        public System.DateTime salesDate { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
