//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shifts
    {
        public int shiftID { get; set; }
        public int workpositionID { get; set; }
        public int employeerID { get; set; }
        public System.DateTime dateShift { get; set; }
        public int typeShift { get; set; }
    
        public virtual Employeers Employeers { get; set; }
        public virtual Workpositions Workpositions { get; set; }
    }
}
