//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Halls
    {
        public Halls()
        {
            this.MovieSales = new HashSet<MovieSales>();
            this.Shows = new HashSet<Shows>();
        }
    
        public int hallID { get; set; }
        public int number { get; set; }
        public string title { get; set; }
        public string matrix { get; set; }
        public int isEnable { get; set; }
    
        public virtual ICollection<MovieSales> MovieSales { get; set; }
        public virtual ICollection<Shows> Shows { get; set; }
    }
}
