//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieSales
    {
        public int moviesalesID { get; set; }
        public int movieID { get; set; }
        public int hallID { get; set; }
        public System.DateTime date { get; set; }
        public string position { get; set; }
    
        public virtual Halls Halls { get; set; }
        public virtual Movies Movies { get; set; }
    }
}
