//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movies
    {
        public Movies()
        {
            this.MovieSales = new HashSet<MovieSales>();
            this.Shows = new HashSet<Shows>();
        }
    
        public int movieID { get; set; }
        public string title { get; set; }
        public decimal price { get; set; }
        public int duration { get; set; }
        public string director { get; set; }
        public string description { get; set; }
        public bool isAvailable { get; set; }
    
        public virtual ICollection<MovieSales> MovieSales { get; set; }
        public virtual ICollection<Shows> Shows { get; set; }
    }
}
