//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shows
    {
        public Shows()
        {
            this.Transations = new HashSet<Transations>();
        }
    
        public int showID { get; set; }
        public int movieID { get; set; }
        public int hallID { get; set; }
        public System.DateTime dateStart { get; set; }
        public System.DateTime dateEnd { get; set; }
        public string matrix { get; set; }
    
        public virtual Halls Halls { get; set; }
        public virtual Movies Movies { get; set; }
        public virtual ICollection<Transations> Transations { get; set; }
    }
}
