//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketSales
    {
        public int ticketID { get; set; }
        public int transationID { get; set; }
        public int amount { get; set; }
    
        public virtual Tickets Tickets { get; set; }
        public virtual Transations Transations { get; set; }
    }
}
